# Nombre del workflow que aparecerá en la pestaña "Actions" de GitHub
name: Deploy to GitHub Pages

# Disparador: ¿Cuándo se ejecuta este workflow?
# Se ejecutará cada vez que haya un "push" (una subida de código) a la rama "main".
on:
  push:
    branches:
      - "main"

# Permisos: Le damos permiso al robot para que pueda escribir en nuestro repositorio.
permissions:
  contents: write

# Tareas: ¿Qué trabajos tiene que hacer el robot?
jobs:
  # Definimos un único trabajo llamado "build-and-deploy"
  build-and-deploy:
    # Máquina virtual: El robot necesita un ordenador para trabajar. Usará uno con Ubuntu.
    runs-on: ubuntu-latest

    # Pasos: La secuencia de comandos que debe ejecutar el robot.
    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instalar y configurar Node.js para poder usar npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # 3. Instalar todas las dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # 4. Construir la aplicación (ejecuta "npm run build")
      - name: Build application
        run: npm run build

      # 5. Desplegar en la rama gh-pages (ejecuta nuestro script "npm run deploy")
      - name: Deploy to gh-pages
        run: npm run deploy
