# Nombre del workflow
name: Deploy to GitHub Pages

# Disparador
on:
  push:
    branches:
      - "main"

# Permisos
permissions:
  contents: write

# Tareas
jobs:
  build-and-deploy:
    # Máquina virtual
    runs-on: ubuntu-latest

    # Pasos
    steps:
      # 1. Descargar el código (igual que antes)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instalar Node.js (igual que antes)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # 3. Instalar dependencias (igual que antes)
      - name: Install dependencies
        run: npm install

      # 4. Construir la aplicación (igual que antes)
      - name: Build application
        run: npm run build

      # 5. Desplegar en gh-pages (¡ESTE ES EL PASO CORREGIDO!)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Usamos una acción especializada
        with:
          # Le pasamos el "DNI" o contraseña temporal y segura que GitHub le da al robot
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Le decimos qué carpeta tiene que publicar
          publish_dir: ./dist